---
- name: Get Subnet facts
  ec2_vpc_subnet_facts:
    aws_access_key: "{{ aws_access_key | default(omit) }}"
    aws_secret_key: "{{ aws_secret_key | default(omit) }}"
    region: "{{ subnet_region | default(aws_region) }}"
    filters:
      "tag:Name": "{{ subnet_tag | upper }}"
  register: subnet_facts
...
